// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package repository

import (
	"database/sql"
)

type Category struct {
	ID      string `json:"id"`
	CatName string `json:"cat_name"`
}

type Photo struct {
	ID        string         `json:"id"`
	ProductID sql.NullInt32  `json:"product_id"`
	Link      sql.NullString `json:"link"`
}

type Product struct {
	ID          int32           `json:"id"`
	ProductName string          `json:"product_name"`
	UserID      sql.NullInt32   `json:"user_id"`
	CatID       sql.NullString  `json:"cat_id"`
	TypeID      sql.NullString  `json:"type_id"`
	Price       sql.NullFloat64 `json:"price"`
	State       sql.NullBool    `json:"state"`
	CreatedTime sql.NullTime    `json:"created_time"`
	ExpiredTime sql.NullTime    `json:"expired_time"`
	Address     sql.NullString  `json:"address"`
	Content     sql.NullString  `json:"content"`
}

type SubCategory struct {
	ID       string         `json:"id"`
	TypeName string         `json:"type_name"`
	CatID    sql.NullString `json:"cat_id"`
}

type User struct {
	ID       int32  `json:"id"`
	Phone    string `json:"phone"`
	Username string `json:"username"`
	Passwd   string `json:"passwd"`
	Address  string `json:"address"`
	Email    string `json:"email"`
	Isadmin  bool   `json:"isadmin"`
}
